#!/bin/sh
# devtmpfs does not get automounted for initramfs

export PATH=/sbin:/bin:/usr/sbin:/usr/bin
/bin/mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

/bin/mount -t proc proc /proc
/bin/mount -o remount,rw /
/bin/mkdir -p /dev/pts
/bin/mkdir -p /dev/shm
/bin/mount -a
/bin/hostname -F /etc/hostname

find /sys -name modalias -exec cat \{\} \; | xargs /sbin/modprobe -a >/dev/null 2>/dev/null

for m in sd_mod sr_mod isofs ext4; do
	modprobe "$m"
done

modprobe usbhid

# make and mount /data
[ -d /data ] || mkdir /data
mount LABEL=DATA /data || true

# bring up loopback interface
ifconfig lo up

# sysctl
sysctl -p

# start services
exec runsvdir -P -s /usr/sbin/runit-signal /service
