all:
	mkdir -p root/bin
	wget https://github.com/brimstone/notminisign/releases/download/0.0.1/notminisign_linux_amd64 -O root/bin/notminisign
	chmod 755 root/bin/notminisign
	tar -cf out.tar -C root .
