#!/bin/bash

kernel="$(curl -s https://www.kernel.org/ | grep -oE 'http[^ ]*tar.xz' | uniq -d | sed 's/^.*linux-//;s/.tar.xz//')"

sed -i "s/KERNEL_VERSION ?= .*$/KERNEL_VERSION ?= $kernel/" Makefile
