#!/bin/sh
# devtmpfs does not get automounted for initramfs

export PATH=/sbin:/bin
mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

mkdir /proc
mount -t proc proc /proc

mkdir /sys
mount -t sysfs sysfs /sys

mount -o remount,rw /

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

mkdir -p /dev/shm

mkdir /tmp
/bin/mount -a
/bin/hostname -F /etc/hostname

find /sys -name modalias -exec cat \{\} \; \
| xargs /sbin/modprobe -a >/dev/null 2>/dev/null

# make and mount /data
[ -d /data ] || mkdir /data
mount LABEL=DATA /data || true

# bring up loopback interface
ifconfig lo up

# sysctl
sysctl -p

# start services
exec runsvdir -P -s /sbin/runit-signal /service
